VIRTUAL-RUNTIME_obmc-host-state-manager = "x86-power-control"
VIRTUAL-RUNTIME_obmc-chassis-state-manager = "x86-power-control"
VIRTUAL-RUNTIME_obmc-sensors-hwmon = "dbus-sensors"
VIRTUAL-RUNTIME_obmc-inventory-manager = "entity-manager"

PREFERRED_PROVIDER_virtual/obmc-chassis-mgmt = "packagegroup-ocp-apps"
PREFERRED_PROVIDER_virtual/obmc-fan-mgmt = "packagegroup-ocp-apps"
PREFERRED_PROVIDER_virtual/obmc-flash-mgmt = "packagegroup-ocp-apps"
PREFERRED_PROVIDER_virtual/obmc-system-mgmt = "packagegroup-ocp-apps"
