require conf/distro/openbmc-phosphor.conf
require conf/distro/include/phosphor-no-webui.inc

U-BMC_VERSION ?= "0.1.0"
DISTRO = "u-bmc"
DISTRO_NAME = "u-bmc"
DISTRO_VERSION = "u-bmc-release-${U-BMC_VERSION}"
EXTENDED_VERSION = "${DISTRO_VERSION}"
DISTROOVERRIDES .= ":u-bmc"

# Possible values: "dev", "prod", "local"
U-BMC_CONFIG ?= "local"
OVERRIDES .= ":${U-BMC_CONFIG}:"
# local config will also include dev config
OVERRIDES:append:local = ":dev:"

DISTRO_FEATURES:remove = "obmc-host-ctl"
DISTRO_FEATURES:remove = "obmc-host-ipmi"
DISTRO_FEATURES:remove = "obmc-phosphor-chassis-mgmt"
DISTRO_FEATURES:remove = "obmc-phosphor-fan-mgmt"
DISTRO_FEATURES:remove = "obmc-phosphor-flash-mgmt"
DISTRO_FEATURES:remove = "obmc-phosphor-system-mgmt"

WATCHDOG_PKG ?= "watchdog"

# Provides reasonable data integrity and faster than sha*
FIT_HASH_ALG = "crc32"
