description: >
    Genesis3 inventory fixups

events:
    - name: Add BMC details
      description: >
          Add the BMC inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/bmc:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Aspeed"
                          type: string
                      Model:
                          value: "AST2500"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Bmc:

    - name: Add PSU0 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply0:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:
  
    - name: Add PSU1 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply1:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:

    - name: Add PSU2 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply2:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:

    - name: Add PSU3 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply3:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:

