[Unit]
After=xyz.openbmc_project.Inventory.Manager.service
Wants=xyz.openbmc_project.Inventory.Manager.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan1.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan2.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan3.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan4.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan5.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan6.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan7.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-fan-Fan8.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-powersupply-ACBEL_PSU1.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-powersupply-ACBEL_PSU2.service
