[Unit]
After=xyz.openbmc_project.Inventory.Manager.service
Wants=xyz.openbmc_project.Inventory.Manager.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan1.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan2.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan3.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan4.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan5.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan6.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan7.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-chassis-ASRock_TURIN2D24TM3_2L_Chassis-Fan8.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-PowerSupply-ACBEL_PSU1.service
Wants=mapper-wait@-xyz-openbmc_project-inventory-system-PowerSupply-ACBEL_PSU2.service
