description: >
    SBP1 inventory fixups

events:
    - name: Add BMC details
      description: >
          Add the BMC inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/bmc:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Aspeed"
                          type: string
                      Model:
                          value: "AST2600"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Bmc:
    - name: Add CPU0
      description: >
          Add the CPU0 inventory path.
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/cpu0:
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Intel"
                          type: string
                      Model:
                          value: "4th Generation Intel Xeon Scalable Processors"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Cpu:
    - name: Add CPU1
      description: >
          Add the CPU1 inventory path.
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/cpu1:
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Intel"
                          type: string
                      Model:
                          value: "4th Generation Intel Xeon Scalable Processors"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Cpu:
    - name: Add CPU2
      description: >
          Add the CPU2 inventory path.
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/cpu2:
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Intel"
                          type: string
                      Model:
                          value: "4th Generation Intel Xeon Scalable Processors"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Cpu:
    - name: Add CPU3
      description: >
          Add the CPU3 inventory path.
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/cpu3:
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Intel"
                          type: string
                      Model:
                          value: "4th Generation Intel Xeon Scalable Processors"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Cpu:
    - name: Add PSU0 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply0:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:
  
    - name: Add PSU1 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply1:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:

    - name: Add PSU2 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply2:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:

    - name: Add PSU3 interface
      description: >
          Add the power supply interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/powersupply3:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Decorator.Asset:
                      Manufacturer:
                          value: "Vicor"
                          type: string
                      Model:
                          value: "BCM 6123"
                          type: string
                  xyz.openbmc_project.Inventory.Item.PowerSupply:

    - name: Add NVMe M.2 interface 1
      description: >
          Add the M.2 NVMe interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/m2_ssd1:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Item.PCIeSlot:

    - name: Add NVMe M.2 interface 2
      description: >
          Add the M.2 NVMe interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/m2_ssd2:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Item.PCIeSlot:

    - name: Add RTC battery
      description: >
          Add the RTC interface on the chassis inventory path
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/motherboard/rtc_bat:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                  xyz.openbmc_project.Inventory.Item.Battery:
