description: >
    ASRock TURIN2D24TM3-2L Fan Inventory

events:
    - name: Add Fan 1
      description: >
          Add Fan 1 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan1:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 1"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 2
      description: >
          Add Fan 2 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan2:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 2"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 3
      description: >
          Add Fan 3 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan3:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 3"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 4
      description: >
          Add Fan 4 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan4:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 4"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 5
      description: >
          Add Fan 5 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan5:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 5"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 6
      description: >
          Add Fan 6 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan6:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 6"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 7
      description: >
          Add Fan 7 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan7:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 7"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
    - name: Add Fan 8
      description: >
          Add Fan 8 to inventory
      type: startup
      actions:
          - name: createObjects
            objs:
                /system/chassis/ASRock_TURIN2D24TM3_2L_Chassis/Fan8:
                  xyz.openbmc_project.Inventory.Item:
                      Present:
                          value: true
                          type: boolean
                      PrettyName:
                          value: "Fan 8"
                          type: string
                  xyz.openbmc_project.Inventory.Item.Fan:
                  xyz.openbmc_project.State.Decorator.OperationalStatus:
                      Functional:
                          value: true
                          type: boolean
