BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "u-bmc-layer"
BBFILE_PATTERN_u-bmc-layer = "^${LAYERDIR}/"
LAYERVERSION_COMPAT_u-bmc-layer = "1"
LAYERSERIES_COMPAT_u-bmc-layer = "whinlatter walnascar"
LAYERDEPENDS_u-bmc-layer += "core phosphor-layer"
